name: "Deploy to server"

on: push



jobs:
  first_jobs:
    runs-on: ubuntu-latest
    
    env:
      CodigoFacilitoHome: "/usr/local"
    steps:
      - id: step_1
        run: echo "mi_variable=Hola Mundo Github" >> $GITHUB_OUTPUT      
      - name: Hola Mundo        
        run: echo "Hola Mundo clase 2."

      - name: Imprime variable de entorno
        run: echo "$CodigoFacilitoHome"
      - run: echo "mi variable paso1: ${{steps.step_1.outputs.mi_variable}}"
  second_job:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: first_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Paso 2
        run: echo "Ejecutando paso 2 ..."
      - name: Imprimiendo contexto
        run: echo "${{github.ref}}"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: 
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
      - run: ls -al
      - run: java -version #java HelloWorldApp.java
      - run: javac HolaMundo.java
      - run: java HolaMundo