name: "Deploy to server"

on: push



jobs:
  first_jobs:
    runs-on: ubuntu-latest
    
    env:
      CodigoFacilitoHome: "/usr/local"
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo clase 2."

      - name: Imprime variable de entorno
        run: echo "$CodigoFacilitoHome"
  second_job:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: first_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Paso 2
        run: echo "Ejecutando paso 2 ..."
      - name: Imprimiendo contexto
        run: echo "${{github.ref}}"
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - run: java HelloWorldApp.java
