name: "Deploy to server"

on: push



jobs:
  first_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo clase 2."
  second_job:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: first_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Paso 2
        run: echo "Ejecutando paso 2 ..."
