name: Deploy

on: push


jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable 
        run: echo "${{secrets.PASSWORD}}"
      - uses: actions/setup-java@v4
        with: 
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: java -version